# Generated by Django 3.2 on 2021-05-27 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userAssements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A1', models.PositiveIntegerField()),
                ('E1', models.PositiveIntegerField()),
                ('P1', models.PositiveIntegerField()),
                ('N1', models.PositiveIntegerField()),
                ('A2', models.PositiveIntegerField()),
                ('H1', models.PositiveIntegerField()),
                ('M1', models.PositiveIntegerField()),
                ('R1', models.PositiveIntegerField()),
                ('M2', models.PositiveIntegerField()),
                ('E2', models.PositiveIntegerField()),
                ('Lon', models.PositiveIntegerField()),
                ('H2', models.PositiveIntegerField()),
                ('P2', models.PositiveIntegerField()),
                ('N2', models.PositiveIntegerField()),
                ('A3', models.PositiveIntegerField()),
                ('N3', models.PositiveIntegerField()),
                ('E3', models.PositiveIntegerField()),
                ('H3', models.PositiveIntegerField()),
                ('R2', models.PositiveIntegerField()),
                ('M3', models.PositiveIntegerField()),
                ('R3', models.PositiveIntegerField()),
                ('P3', models.PositiveIntegerField()),
                ('hap', models.PositiveIntegerField()),
                ('Q1', models.CharField(blank=True, max_length=200)),
                ('Q2', models.CharField(blank=True, max_length=200)),
                ('Q3', models.CharField(blank=True, max_length=200)),
                ('Q4', models.CharField(blank=True, max_length=200)),
                ('Q5', models.CharField(blank=True, max_length=200)),
                ('Q6', models.CharField(blank=True, max_length=200)),
                ('Q7', models.CharField(blank=True, max_length=200)),
                ('Q8', models.CharField(blank=True, max_length=200)),
                ('Q9', models.CharField(blank=True, max_length=200)),
                ('Q10', models.CharField(blank=True, max_length=200)),
                ('Q11', models.CharField(blank=True, max_length=200)),
                ('Q12', models.CharField(blank=True, max_length=200)),
                ('going_beyond_stress', models.BooleanField(default=False)),
                ('finding_sustained_happiness', models.BooleanField(default=False)),
                ('mental_emotional_wellness', models.BooleanField(default=False)),
                ('positive_parenting', models.BooleanField(default=False)),
                ('healthy_relationship', models.BooleanField(default=False)),
                ('accelerated_professional_growth', models.BooleanField(default=False)),
                ('healthy_lifestyle', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
