# Generated by Django 3.2 on 2021-05-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userAssements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField()),
                ('absorbed', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
