# Generated by Django 3.2 on 2021-05-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userassements',
            name='absorbed',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='progress',
        ),
        migrations.AddField(
            model_name='userassements',
            name='A1',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
