# Generated by Django 3.2 on 2021-05-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassements',
            name='A1',
            field=models.PositiveIntegerField(help_text='abc'),
        ),
    ]
