# Generated by Django 3.2 on 2021-05-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_userassements_a1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassements',
            name='A1',
            field=models.PositiveIntegerField(),
        ),
    ]
