# Generated by Django 3.2 on 2021-05-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_alter_userassements_a1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userassements',
            old_name='A1',
            new_name='How_much_of_the_time_do_you_feel_you_are_making_progress_towards_accomplishing_your_goals',
        ),
    ]
