# Generated by Django 3.2 on 2021-05-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_auto_20210512_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='userassements',
            name='Q1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userassements',
            name='Q10',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userassements',
            name='Q11',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userassements',
            name='Q12',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userassements',
            name='Q2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userassements',
            name='Q3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userassements',
            name='Q4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userassements',
            name='Q5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userassements',
            name='Q6',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userassements',
            name='Q7',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userassements',
            name='Q8',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userassements',
            name='Q9',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userassements',
            name='accelerated_professional_growth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userassements',
            name='finding_sustained_happiness',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userassements',
            name='going_beyond_stress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userassements',
            name='healthy_lifestyle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userassements',
            name='healthy_relationship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userassements',
            name='mental_emotional_wellness',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userassements',
            name='positive_parenting',
            field=models.BooleanField(default=False),
        ),
    ]
