# Generated by Django 3.2 on 2021-05-27 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_rename_a1_userassements_how_much_of_the_time_do_you_feel_you_are_making_progress_towards_accomplishi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userassements',
            old_name='E1',
            new_name='How_often_do_you_become_absorbed_in_what_you_are_doing',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='P1',
            new_name='In_general_how_often_do_you_feel_joyful',
        ),
    ]
