# Generated by Django 3.2 on 2021-05-27 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_auto_20210527_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userassements',
            old_name='A2',
            new_name='Compared_to_others_of_your_same_age_and_sex_how_is_your_health',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='A3',
            new_name='How_lonely_do_you_feel_in_your_daily_life',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='E2',
            new_name='How_often_are_you_able_to_handle_your_responsibilities',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='E3',
            new_name='How_often_do_you_achieve_the_important_goals_you_have_set_for_yourself',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='H1',
            new_name='How_often_do_you_lose_track_of_time_while_doing_something_you_enjoy',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='H2',
            new_name='How_satisfied_are_you_with_your_current_physical_health',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='H3',
            new_name='How_satisfied_are_you_with_your_relationships',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='Lon',
            new_name='In_general_how_often_do_you_feel_angry',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='M1',
            new_name='In_general_how_often_do_you_feel_anxious',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='M2',
            new_name='In_general_how_often_do_you_feel_positive',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='M3',
            new_name='In_general_how_often_do_you_feel_sad',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='N1',
            new_name='In_general_how_would_you_say_your_health_is',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='N2',
            new_name='In_general_to_what_extent_do_you_feel_contented',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='N3',
            new_name='In_general_to_what_extent_do_you_feel_excited_and_interested_in_things',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='P2',
            new_name='In_general_to_what_extent_do_you_feel_that_what_you_do_in_your_life_is_valuable_and_worthwhile',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='P3',
            new_name='In_general_to_what_extent_do_you_lead_a_purposeful_and_meaningful_life',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='R1',
            new_name='Taking_all_things_together_how_happy_would_you_say_you_are',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='R2',
            new_name='To_what_extent_do_you_feel_loved',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='R3',
            new_name='To_what_extent_do_you_generally_feel_you_have_a_sense_of_direction_in_your_life',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='hap',
            new_name='To_what_extent_do_you_receive_help_and_support_from_others_when_you_need_it',
        ),
    ]
