# Generated by Django 3.2 on 2021-05-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_auto_20210527_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userassements',
            old_name='Q1',
            new_name='Bouts_of_boredeom_or_feeling_low',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='Q10',
            new_name='Difficulty_falling_asleep_or_finding_yourself_over_sleeping',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='Q11',
            new_name='Discomfort_in_communicating_with_people_in_your_work_place_or_personal_life',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='Q12',
            new_name='Experiencing_Irritation_or_anger_with_things_outside_of_your_control',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='Q2',
            new_name='Facing_Health_Issues_like_headaches_stomach_upsets_rashes_on_the_body_etc',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='Q3',
            new_name='Feeling_upset_because_of_something_that_happened_unexpectedly',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='Q4',
            new_name='Finding_it_difficult_to_cope_with_all_the_things_that_you_have_to_do',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='Q5',
            new_name='Finding_the_need_to_take_intoxicants_or_stimulants',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='Q6',
            new_name='Getting_tired_easily_or_experiencing_fatigue',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='Q7',
            new_name='Having_Mood_Swings',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='Q8',
            new_name='Irregular_Eating_Habits_like_eating_too_much_or_too_little',
        ),
        migrations.RenameField(
            model_name='userassements',
            old_name='Q9',
            new_name='Tension_in_the_body_like_tense_muscles_sore_back_or_neck',
        ),
    ]
