# Generated by Django 3.2 on 2021-05-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_auto_20210527_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassements',
            name='Bouts_of_boredeom_or_feeling_low',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userassements',
            name='Difficulty_falling_asleep_or_finding_yourself_over_sleeping',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userassements',
            name='Discomfort_in_communicating_with_people_in_your_work_place_or_personal_life',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userassements',
            name='Experiencing_Irritation_or_anger_with_things_outside_of_your_control',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userassements',
            name='Facing_Health_Issues_like_headaches_stomach_upsets_rashes_on_the_body_etc',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userassements',
            name='Feeling_upset_because_of_something_that_happened_unexpectedly',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userassements',
            name='Finding_it_difficult_to_cope_with_all_the_things_that_you_have_to_do',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userassements',
            name='Finding_the_need_to_take_intoxicants_or_stimulants',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userassements',
            name='Getting_tired_easily_or_experiencing_fatigue',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userassements',
            name='Having_Mood_Swings',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userassements',
            name='Irregular_Eating_Habits_like_eating_too_much_or_too_little',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userassements',
            name='Tension_in_the_body_like_tense_muscles_sore_back_or_neck',
            field=models.PositiveIntegerField(),
        ),
    ]
