# Generated by Django 3.2 on 2021-06-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_alter_userassements_how_much_of_the_time_do_you_feel_you_are_making_progress_towards_accomplishing_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userassements',
            name='Bouts_of_boredeom_or_feeling_low',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='Compared_to_others_of_your_same_age_and_sex_how_is_your_health',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='Difficulty_falling_asleep_or_finding_yourself_over_sleeping',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='Discomfort_in_communicating_with_people_in_your_work_place_or_personal_life',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='Experiencing_Irritation_or_anger_with_things_outside_of_your_control',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='Facing_Health_Issues_like_headaches_stomach_upsets_rashes_on_the_body_etc',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='Feeling_upset_because_of_something_that_happened_unexpectedly',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='Finding_it_difficult_to_cope_with_all_the_things_that_you_have_to_do',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='Finding_the_need_to_take_intoxicants_or_stimulants',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='Getting_tired_easily_or_experiencing_fatigue',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='Having_Mood_Swings',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='How_lonely_do_you_feel_in_your_daily_life',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='How_much_of_the_time_do_you_feel_you_are_making_progress_towards_accomplishing_your_goals',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='How_often_are_you_able_to_handle_your_responsibilities',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='How_often_do_you_achieve_the_important_goals_you_have_set_for_yourself',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='How_often_do_you_become_absorbed_in_what_you_are_doing',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='How_often_do_you_lose_track_of_time_while_doing_something_you_enjoy',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='How_satisfied_are_you_with_your_current_physical_health',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='How_satisfied_are_you_with_your_relationships',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='In_general_how_often_do_you_feel_angry',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='In_general_how_often_do_you_feel_anxious',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='In_general_how_often_do_you_feel_joyful',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='In_general_how_often_do_you_feel_positive',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='In_general_how_often_do_you_feel_sad',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='In_general_how_would_you_say_your_health_is',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='In_general_to_what_extent_do_you_feel_contented',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='In_general_to_what_extent_do_you_feel_excited_and_interested_in_things',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='In_general_to_what_extent_do_you_feel_that_what_you_do_in_your_life_is_valuable_and_worthwhile',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='In_general_to_what_extent_do_you_lead_a_purposeful_and_meaningful_life',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='Irregular_Eating_Habits_like_eating_too_much_or_too_little',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='Taking_all_things_together_how_happy_would_you_say_you_are',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='Tension_in_the_body_like_tense_muscles_sore_back_or_neck',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='To_what_extent_do_you_feel_loved',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='To_what_extent_do_you_generally_feel_you_have_a_sense_of_direction_in_your_life',
        ),
        migrations.RemoveField(
            model_name='userassements',
            name='To_what_extent_do_you_receive_help_and_support_from_others_when_you_need_it',
        ),
        migrations.AddField(
            model_name='userassements',
            name='A1',
            field=models.PositiveIntegerField(default=0, verbose_name='1. How often do you feel you are making progress towards accomplishing your goals? (0 - never, 5 - always)'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='A2',
            field=models.PositiveIntegerField(default=0, verbose_name='5. How often do you achieve the important goals you have set for yourself? (0 - never, 5 - always)'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='A3',
            field=models.PositiveIntegerField(default=0, verbose_name='15. How often are you able to handle your responsibilities? (0 - never, 5 - always)'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='E1',
            field=models.PositiveIntegerField(default=0, verbose_name='2. How often do you become absorbed in what you are doing? (0 - never, 5 - always)'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='E2',
            field=models.PositiveIntegerField(default=0, verbose_name='10. In general, to what extent do you feel excited and interested in things? (0 - not at all, 5 - completely)'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='E3',
            field=models.PositiveIntegerField(default=0, verbose_name='17. How often do you lose track of time while doing something you enjoy? (0 - never, 5 - always)'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='H1',
            field=models.PositiveIntegerField(default=0, verbose_name='6. In general, how would you rate your health? (0 - terrible, 5 - excellent)'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='H2',
            field=models.PositiveIntegerField(default=0, verbose_name='12. How satisfied are you with your current physical health? (0 - not at all, 5 - completely)'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='H3',
            field=models.PositiveIntegerField(default=0, verbose_name='18. Compared to others of your same age and sex, how is your health? (0 - terrible, 5 - excellent)'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='Lon',
            field=models.PositiveIntegerField(default=0, verbose_name='11. How lonely do you feel in your daily life? (0 - not at all, 5 - completely)'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='M1',
            field=models.PositiveIntegerField(default=0, verbose_name='7. In general, to what extent do you lead a purposeful and meaningful life? (0 - not at all, 5 - completely)'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='M2',
            field=models.PositiveIntegerField(default=0, verbose_name='9. In general, to what extent do you feel that what you do in your life is valuable and worthwhile? (0 - not at all, 5 - completely)'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='M3',
            field=models.PositiveIntegerField(default=0, verbose_name='20. To what extent do you generally feel you have a sense of direction in your life? (0 - not at all, 5 - completely)'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='N1',
            field=models.PositiveIntegerField(default=0, verbose_name='4. In general, how often do you feel anxious? (0 - never, 5 - always)'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='N2',
            field=models.PositiveIntegerField(default=0, verbose_name='14. In general, how often do you feel angry? (0 - never, 5 - always)'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='N3',
            field=models.PositiveIntegerField(default=0, verbose_name='16. In general, how often do you feel sad? (0 - never, 5 - always)'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='P1',
            field=models.PositiveIntegerField(default=0, verbose_name='3. In general, how often do you feel joyful? (0 - never, 5 - always)'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='P2',
            field=models.PositiveIntegerField(default=0, verbose_name='13. In general, how often do you feel positive? (0 - never, 5 - always)'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='P3',
            field=models.PositiveIntegerField(default=0, verbose_name='22. In general, to what extent do you feel contented? (0 - not at all, 5 - completely)'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='Q1',
            field=models.PositiveIntegerField(default=0, verbose_name='1. Tension in the body, like tense muscles, sore back or neck'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='Q10',
            field=models.PositiveIntegerField(default=0, verbose_name='10. Feeling upset because of something that happened unexpectedly'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='Q11',
            field=models.PositiveIntegerField(default=0, verbose_name='11. Finding it difficult to cope with all the things that you have to do'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='Q12',
            field=models.PositiveIntegerField(default=0, verbose_name='12. Finding the need to take intoxicants or stimulants'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='Q2',
            field=models.PositiveIntegerField(default=0, verbose_name='2. Difficulty falling asleep or finding yourself over sleeping?'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='Q3',
            field=models.PositiveIntegerField(default=0, verbose_name='3. Having Mood Swings'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='Q4',
            field=models.PositiveIntegerField(default=0, verbose_name='4. Experiencing Irritation or anger with things outside of your control'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='Q5',
            field=models.PositiveIntegerField(default=0, verbose_name='5. Facing Health Issues like headaches, stomach upsets, rashes on the body etc'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='Q6',
            field=models.PositiveIntegerField(default=0, verbose_name='6. Irregular Eating Habits like eating too much or too little'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='Q7',
            field=models.PositiveIntegerField(default=0, verbose_name='7. Discomfort in communicating with people in your work place or personal life'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='Q8',
            field=models.PositiveIntegerField(default=0, verbose_name='8. Getting tired easily or experiencing fatigue'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='Q9',
            field=models.PositiveIntegerField(default=0, verbose_name='9. Bouts of boredeom or feeling low'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='R1',
            field=models.PositiveIntegerField(default=0, verbose_name='8. To what extent do you receive help and support from others when you need it? (0 - not at all, 5 - completely)'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='R2',
            field=models.PositiveIntegerField(default=0, verbose_name='19. To what extent do you feel loved? (0 - not at all, 5 - completely)'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='R3',
            field=models.PositiveIntegerField(default=0, verbose_name='21. How satisfied are you with your relationships? (0 - not at all, 5 - completely)'),
        ),
        migrations.AddField(
            model_name='userassements',
            name='hap',
            field=models.PositiveIntegerField(default=0, verbose_name='23. Taking all things together, how happy would you say you are? (0 - not at all, 5 - completely)'),
        ),
        migrations.AlterField(
            model_name='userassements',
            name='accelerated_professional_growth',
            field=models.BooleanField(default=False, verbose_name='Accelerated Professional Growth'),
        ),
        migrations.AlterField(
            model_name='userassements',
            name='coping_with_the_covid_situation',
            field=models.BooleanField(default=False, verbose_name='Coping with the Covid Situation'),
        ),
        migrations.AlterField(
            model_name='userassements',
            name='finding_sustained_happiness',
            field=models.BooleanField(default=False, verbose_name='Finding Sustained Happiness'),
        ),
        migrations.AlterField(
            model_name='userassements',
            name='going_beyond_stress',
            field=models.BooleanField(default=False, verbose_name='Going Beyond Stress'),
        ),
        migrations.AlterField(
            model_name='userassements',
            name='healthy_lifestyle',
            field=models.BooleanField(default=False, verbose_name='Healthy Lifestyle'),
        ),
        migrations.AlterField(
            model_name='userassements',
            name='healthy_relationship',
            field=models.BooleanField(default=False, verbose_name='Healthy Relationships'),
        ),
        migrations.AlterField(
            model_name='userassements',
            name='mental_emotional_wellness',
            field=models.BooleanField(default=False, verbose_name='Mental & Emotional Wellness'),
        ),
        migrations.AlterField(
            model_name='userassements',
            name='positive_parenting',
            field=models.BooleanField(default=False, verbose_name='Positive Parenting'),
        ),
    ]
