# Generated by Django 3.2 on 2021-06-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0014_alter_userassements_assesment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userassements',
            old_name='assesment_user',
            new_name='user',
        ),
    ]
